### ISSUE TITLE
Xcode7 compile error

### ISSUE THREAD

**Issue by lxkbest** [hyperoslo/Simulator#2]
Need to be swift3 compile ？

**Comment by onmyway133** [comment]
@lxkbest Hi, we just accepted this PR https://github.com/hyperoslo/Simulator/pull/1 so it is in Swift 3 now

**Comment by zenangst** [comment]
@lxkbest hey, if you want to compile it in Xcode 7, you can checkout an older commit and build from that instead of `master` :) Hope that helps!
